apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: asset2
spec:
  secretRef: 
    name: asset2
  details:
    dataFormat: pdf
    connection:
      name: s3
      s3:
        endpoint: "localstack.fybrik-notebook-sample.svc.cluster.local:4566"
        bucket: "demo"
        object_key: "sample2.pdf"
  metadata:
    name: Synthetic Financial Datasets For Fraud Detection
    geography: theshire 
    tags:
      finance: false
