apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: asset1
spec:
  secretRef: 
    name: asset1
  details:
    dataFormat: json
    connection:
      name: s3
      s3:
        endpoint: "localstack.fybrik-notebook-sample.svc.cluster.local:4566"
        bucket: "demo"
        object_key: "sample1.json"
  metadata:
    name: Synthetic Financial Datasets For Fraud Detection
    geography: theshire 
    tags:
      finance: true
